language: go

services:
  - docker

script: make build

deploy:
  - provider: script
    script: make release DOCKER_USERNAME="$DOCKER_USERNAME" DOCKER_PASSWORD="$DOCKER_PASSWORD"
    on:
      branch: master
